PR: adds constrain macro to use eloquent for retrieving records. Fixes pagination when simple where() statements are used.
suenert/laravel-scout-tntsearch-driver pull request #1
Opened 2018-06-21 15:26 UTC by michaelklopf

2018-06-21 15:28 UTC, michaelklopf commented
`$maxResultSet` und `filtered` haben nun beide die gleichen Ergebnisse, jedoch hat erst $filtered die richtige Sortierung. Da sollten wir noch einmal darüber reden.

2018-06-22 09:19 UTC, thoresuenert commented
das kann eigentlich nicht sein, wenn wir über die role ergebnisse ausgrenzen sollte das resultset kleiner sein als filtered

2018-06-22 10:00 UTC, michaelklopf commented
Beim `$maxResultSet` nutzen wir `$results['ids']` für das whereIn, was dann auch bei `$filtered` genutzt wird und daher sind beide Sets gleich groß.

2018-06-27 08:27 UTC, thoresuenert commented on src/Engines/TNTSearchEngine.php
> +            ->pluck('id');
@michaelklopf hier muessen wir `id` noch durch keyName ersetzen.

2018-06-27 08:28 UTC, thoresuenert requested changes
die eine sache mit der id noch dann sind wir wohl durch.

2018-06-27 08:53 UTC, michaelklopf commented on src/Engines/TNTSearchEngine.php
> +            ->pluck('id');
Habe ich ersetzt.

2018-06-27 09:20 UTC, thoresuenert approved these changes

2018-06-27 09:22 UTC, merged